_target_: driverl.nuplan.controller.DriveRLOneStageController
_convert_: 'all'
device: cuda
dynamics_model: nuplan_bicycle_model
frame_time_interval: 0.1
enable_dynamics_noise: false
dynamics_noise_scale: 1.0
min_jerk_long: -8.0
max_jerk_long: 5.0
positive_jerk_limit_when_nonnegative_acc: 1.0
min_jerk_lat: -1.0
max_jerk_lat: 1.0
min_a_long: -6.5
max_a_long: 1.5
min_a_lat: -3.0
max_a_lat: 3.0
control_delay_frame: 0
control_delay_smoothing: 0.0
lateral_mode_transition_speed: 5.0
lateral_mode_transition_width: 0.3
lateral_action_space_shape_gamma: 2.0
max_tire_angle_rate_lower_bound: 0.03
max_tire_angle_rate_upper_bound: 0.21
max_tire_angle_rate_gain: 0.973
num_jerk_lat_actions: 64
num_jerk_long_actions: 24
nuplan_bicycle_accel_time_constant: 0.2
nuplan_bicycle_steering_angle_time_constant: 0.05
nuplan_bicycle_max_steering_angle: 1.0471975511965976
nuplan_bicycle_max_acceleration: 4.0
nuplan_bicycle_max_steering_rate: 0.8
nuplan_bicycle_wheelbase: 3.089
nuplan_bicycle_rear_axle_to_center: 1.461
